### ISSUE TITLE
"Shadow field languageManager was not located in target class net.minecraft.client.Minecraft."

### ISSUE THREAD

**Issue by obr-09** [SpongePowered/McTester#8]
Launching the tests using gradle no longer works (it used to work 13 days ago).

I copied the debug test output with stacktrace, and from what I can tell it no longer find the shadow field languageManager in the net.minecraft.client.Minecraft class. I guess something has changed during those last 13 days ?

Here is the gist of the gradle debug : 
https://gist.github.com/zessirb/416bf8840638d1ab729ac4b56e97da0e

And here is the build.gradle I'm using (it didn't change and was working before) : 
https://github.com/OnapleRPG/Harvester/blob/master/build.gradle

**Comment by Aaron1011** [comment]
You'll need to change `mappings = "snapshot_20171007"` to `mappings = "snapshot_20180808"` in your `build.gradle`, since Sponge bumped its mappings version.

Unforuntately, this kind of thing is necessary until a few Mixin issues are resolved.
